/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Daniel Poot
 */
public class IngresoHorario extends javax.swing.JFrame {
    private Conectar ConexionRH = new Conectar();
    /**
     * Creates new form IngresoHorario
     */
    public IngresoHorario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTimeChooserDemo1 = new lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo();
        jTimeChooserDemo2 = new lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo();
        TituloRH = new javax.swing.JLabel();
        DiaHorario = new javax.swing.JLabel();
        IngreDiasRH = new javax.swing.JTextField();
        HoraInicioRH = new javax.swing.JLabel();
        HoraSalidaRH = new javax.swing.JLabel();
        BtSalirRH = new javax.swing.JButton();
        BtRegistrarRH = new javax.swing.JButton();
        IngreHoraInicioRH = new javax.swing.JTextField();
        IngreMinutoInicioRH = new javax.swing.JTextField();
        IngreHoraSalidaRH = new javax.swing.JTextField();
        IngreMinutoSalidaRH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloRH.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TituloRH.setText("Registrar nuevo Horario");

        DiaHorario.setText("Dia/s : ");

        IngreDiasRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreDiasRHActionPerformed(evt);
            }
        });

        HoraInicioRH.setText("Hora de inicio : ");

        HoraSalidaRH.setText("Hora de salida : ");

        BtSalirRH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48.png"))); // NOI18N
        BtSalirRH.setText("Salir");
        BtSalirRH.setBorder(null);
        BtSalirRH.setBorderPainted(false);
        BtSalirRH.setContentAreaFilled(false);
        BtSalirRH.setMaximumSize(new java.awt.Dimension(105, 48));
        BtSalirRH.setMinimumSize(new java.awt.Dimension(105, 48));
        BtSalirRH.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48P.png"))); // NOI18N
        BtSalirRH.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48S.png"))); // NOI18N
        BtSalirRH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtSalirRHMouseClicked(evt);
            }
        });
        BtSalirRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirRHActionPerformed(evt);
            }
        });

        BtRegistrarRH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48.png"))); // NOI18N
        BtRegistrarRH.setText("Registrar");
        BtRegistrarRH.setBorder(null);
        BtRegistrarRH.setBorderPainted(false);
        BtRegistrarRH.setContentAreaFilled(false);
        BtRegistrarRH.setMaximumSize(new java.awt.Dimension(96, 96));
        BtRegistrarRH.setMinimumSize(new java.awt.Dimension(96, 96));
        BtRegistrarRH.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48P.png"))); // NOI18N
        BtRegistrarRH.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48S.png"))); // NOI18N
        BtRegistrarRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegistrarRHActionPerformed(evt);
            }
        });

        jLabel1.setText("Hora");
        jLabel1.setMaximumSize(new java.awt.Dimension(45, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(45, 16));

        jLabel2.setText("Minutos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiaHorario)
                    .addComponent(HoraInicioRH)
                    .addComponent(HoraSalidaRH)
                    .addComponent(BtSalirRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngreDiasRH, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngreHoraSalidaRH, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(IngreHoraInicioRH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngreMinutoSalidaRH, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(IngreMinutoInicioRH)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BtRegistrarRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TituloRH)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloRH, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaHorario)
                    .addComponent(IngreDiasRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraInicioRH)
                    .addComponent(IngreHoraInicioRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngreMinutoInicioRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraSalidaRH)
                    .addComponent(IngreHoraSalidaRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngreMinutoSalidaRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalirRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtRegistrarRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreDiasRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreDiasRHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreDiasRHActionPerformed

    private void BtSalirRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirRHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSalirRHActionPerformed

    private void BtSalirRHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtSalirRHMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtSalirRHMouseClicked

    private void BtRegistrarRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegistrarRHActionPerformed
        // TODO add your handling code here:
        int Second = 0;
        
        String Dias = this.IngreDiasRH.getText();
        int HoraInicio = Integer.parseInt(this.IngreHoraInicioRH.getText());
        int MinutosInicio = Integer.parseInt(this.IngreMinutoInicioRH.getText());
        int HoraSalida = Integer.parseInt(this.IngreHoraSalidaRH.getText());
        int MinutosSalida = Integer.parseInt(this.IngreMinutoSalidaRH.getText());
        
        
        //Convertimos los datos de Hora y minutos, tanto como de entrada como de salida, a objetos de timpo hora con Local time
        
        //LocalTime NHoraInicio = LocalTime.of(HoraInicio, MinutosInicio);
        //LocalTime NHoraSalida = LocalTime.of(HoraSalida, MinutosSalida);
        
        java.sql.Time NHoraInicio = new java.sql.Time(HoraInicio,MinutosInicio, Second);
        java.sql.Time NHoraSalida = new java.sql.Time(HoraSalida, MinutosSalida, Second);
        
        
        Horario NHorario = new Horario(Dias, NHoraInicio, NHoraSalida);
        
         PreparedStatement PstH = null;
        try{
            PstH = ConexionRH.getConnection().prepareStatement("INSERT INTO horario VALUES (NULL,?,?,?)");
            
            PstH.setString(1, NHorario.getDia());
            PstH.setTime(2, NHorario.getHoraEntrada());
            PstH.setTime(3, NHorario.getHoraSalida());
            
            
            
            PstH.executeUpdate();
            
            
        }catch(Exception Ex){
            JOptionPane.showMessageDialog(null, "Error " + Ex);
        
    }
        
        
        
    }//GEN-LAST:event_BtRegistrarRHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtRegistrarRH;
    private javax.swing.JButton BtSalirRH;
    private javax.swing.JLabel DiaHorario;
    private javax.swing.JLabel HoraInicioRH;
    private javax.swing.JLabel HoraSalidaRH;
    private javax.swing.JTextField IngreDiasRH;
    private javax.swing.JTextField IngreHoraInicioRH;
    private javax.swing.JTextField IngreHoraSalidaRH;
    private javax.swing.JTextField IngreMinutoInicioRH;
    private javax.swing.JTextField IngreMinutoSalidaRH;
    private javax.swing.JLabel TituloRH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo jTimeChooserDemo1;
    private lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo jTimeChooserDemo2;
    // End of variables declaration//GEN-END:variables
}
