/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Login.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Poot
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void Limpiar() {
        IngresaUsuario.setText("");
        IngresaPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloEscuela = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JLabel();
        TxtContraseña = new javax.swing.JLabel();
        IngresaUsuario = new javax.swing.JTextField();
        IngresaPassword = new javax.swing.JPasswordField();
        BtSalirLogin = new javax.swing.JButton();
        BtIngresarLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloEscuela.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TituloEscuela.setText("Escuela de Natacion ");

        TxtUsuario.setText("Usuario : ");

        TxtContraseña.setText("Contraseña : ");

        IngresaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresaUsuarioActionPerformed(evt);
            }
        });

        IngresaPassword.setText("Password");

        BtSalirLogin.setText("Salir");
        BtSalirLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtSalirLoginMouseClicked(evt);
            }
        });
        BtSalirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirLoginActionPerformed(evt);
            }
        });

        BtIngresarLogin.setText("Ingresar");
        BtIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIngresarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtContraseña)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IngresaPassword))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtUsuario)
                                .addGap(29, 29, 29)
                                .addComponent(IngresaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtSalirLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtIngresarLogin)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtUsuario)
                    .addComponent(IngresaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtContraseña)
                    .addComponent(IngresaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalirLogin)
                    .addComponent(BtIngresarLogin))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresaUsuarioActionPerformed

    private void BtSalirLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtSalirLoginMouseClicked
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_BtSalirLoginMouseClicked

    private void BtSalirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSalirLoginActionPerformed

    private void BtIngresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIngresarLoginActionPerformed
        // TODO add your handling code here:
        
        SQLUsuario modSql = new SQLUsuario();
        Usuario mod = new Usuario();
        
        String pass = new String(IngresaPassword.getPassword());
        
        if (!IngresaUsuario.getText().equals("") && !pass.equals("")) {
            
            
            mod.setUsuario(IngresaUsuario.getText());
            mod.setPassword(IngresaPassword.getText());
            
            if (modSql.Login(mod)) {
                
                
                Menu frmMenu = new Menu(mod);
                frmMenu.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
                Limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
        }
        
        this.dispose();
    }//GEN-LAST:event_BtIngresarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtIngresarLogin;
    private javax.swing.JButton BtSalirLogin;
    private javax.swing.JPasswordField IngresaPassword;
    private javax.swing.JTextField IngresaUsuario;
    private javax.swing.JLabel TituloEscuela;
    private javax.swing.JLabel TxtContraseña;
    private javax.swing.JLabel TxtUsuario;
    // End of variables declaration//GEN-END:variables
}
