/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modulos.Alumno;

/**
 *
 * @author Daniel Poot
 */
public class PagarArticulo extends javax.swing.JFrame {

    /**
     * Creates new form PagarArticulo
     */
    public PagarArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArticuloPA = new javax.swing.JLabel();
        PrecioArticuloPA = new javax.swing.JLabel();
        NumArticuloPA = new javax.swing.JLabel();
        IngreArticuloPA = new javax.swing.JTextField();
        IngrePrecioArticuloPA = new javax.swing.JTextField();
        IngreNumArticuloPA = new javax.swing.JTextField();
        TituloPagoArticulo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TiempoPagoPA = new javax.swing.JLabel();
        IngrePrimerPago = new javax.swing.JTextField();
        PrimerPagoPA = new javax.swing.JLabel();
        SegundoPagoPA = new javax.swing.JLabel();
        IngreSegundoPago = new javax.swing.JTextField();
        BtGuardarPagoA = new javax.swing.JButton();
        BtRegresarPagoA = new javax.swing.JButton();
        AlumnoPA = new javax.swing.JLabel();
        ComboAlumnosPA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ArticuloPA.setText("Articulo : ");

        PrecioArticuloPA.setText("Precio del Articulo : ");

        NumArticuloPA.setText("Numero de Articulos : ");

        IngreArticuloPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreArticuloPAActionPerformed(evt);
            }
        });

        IngrePrecioArticuloPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngrePrecioArticuloPAActionPerformed(evt);
            }
        });

        IngreNumArticuloPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreNumArticuloPAActionPerformed(evt);
            }
        });

        TituloPagoArticulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloPagoArticulo.setText("Pago de Articulo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de Pago", "1 Pago", "2 Pagos" }));

        TiempoPagoPA.setText("Tiempo de Pago:");

        PrimerPagoPA.setText("Primer Pago : ");

        SegundoPagoPA.setText("Segundo Pago :");

        BtGuardarPagoA.setText("Guardar");
        BtGuardarPagoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtGuardarPagoAMouseClicked(evt);
            }
        });

        BtRegresarPagoA.setText("Regresar");

        AlumnoPA.setText("Alumno :");

        ComboAlumnosPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAlumnosPAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtRegresarPagoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtGuardarPagoA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NumArticuloPA)
                                    .addComponent(PrecioArticuloPA)
                                    .addComponent(ArticuloPA)
                                    .addComponent(TiempoPagoPA)
                                    .addComponent(PrimerPagoPA)
                                    .addComponent(SegundoPagoPA)
                                    .addComponent(AlumnoPA))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IngrePrimerPago)
                                    .addComponent(IngreArticuloPA)
                                    .addComponent(IngrePrecioArticuloPA)
                                    .addComponent(IngreNumArticuloPA)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IngreSegundoPago)
                                    .addComponent(ComboAlumnosPA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(TituloPagoArticulo)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(TituloPagoArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlumnoPA)
                    .addComponent(ComboAlumnosPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArticuloPA)
                    .addComponent(IngreArticuloPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioArticuloPA)
                    .addComponent(IngrePrecioArticuloPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumArticuloPA)
                    .addComponent(IngreNumArticuloPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiempoPagoPA))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngrePrimerPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrimerPagoPA))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegundoPagoPA)
                    .addComponent(IngreSegundoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGuardarPagoA)
                    .addComponent(BtRegresarPagoA))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreArticuloPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreArticuloPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreArticuloPAActionPerformed

    private void IngrePrecioArticuloPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngrePrecioArticuloPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngrePrecioArticuloPAActionPerformed

    private void IngreNumArticuloPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreNumArticuloPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreNumArticuloPAActionPerformed

    private void ComboAlumnosPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAlumnosPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAlumnosPAActionPerformed

    private void BtGuardarPagoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtGuardarPagoAMouseClicked
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_BtGuardarPagoAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlumnoPA;
    private javax.swing.JLabel ArticuloPA;
    private javax.swing.JButton BtGuardarPagoA;
    private javax.swing.JButton BtRegresarPagoA;
    private javax.swing.JComboBox<Alumno> ComboAlumnosPA;
    private javax.swing.JTextField IngreArticuloPA;
    private javax.swing.JTextField IngreNumArticuloPA;
    private javax.swing.JTextField IngrePrecioArticuloPA;
    private javax.swing.JTextField IngrePrimerPago;
    private javax.swing.JTextField IngreSegundoPago;
    private javax.swing.JLabel NumArticuloPA;
    private javax.swing.JLabel PrecioArticuloPA;
    private javax.swing.JLabel PrimerPagoPA;
    private javax.swing.JLabel SegundoPagoPA;
    private javax.swing.JLabel TiempoPagoPA;
    private javax.swing.JLabel TituloPagoArticulo;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
