/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Clases.*;
import Login.Usuario;
import Modulos.Maestro;
import static Vista.RAsistenciaAlumno.VAsistenciaA;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Poot
 */
public class RAsistenciaMaestro extends javax.swing.JFrame {
    Conectar RAsitenciaConexion = new Conectar();
    public static VAsistencia VAsistenciaM;
    Usuario Mod;
    /** Creates new form RAsistenciaAlumno */
     public RAsistenciaMaestro(){
         initComponents();
     }
    
    
    public RAsistenciaMaestro(Usuario Mod) {
        initComponents();
        Maestro ComboMaestroM = new Maestro();
        ComboMaestroM.MostrarMaestros(ComboMaestroRA);
        Asistencia ComboAsistenciaM = new Asistencia();
        ComboAsistenciaM.MostrarTipoAsistencia(ComboTipoAsistenciaM);
        this.Mod = Mod;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloAsistenciaM = new javax.swing.JLabel();
        CalendarAsistenciaM = new com.toedter.calendar.JDateChooser();
        FechaAsistenciaM = new javax.swing.JLabel();
        ComboTipoAsistenciaM = new javax.swing.JComboBox<>();
        TipoAsistenciaM = new javax.swing.JLabel();
        RegresarAsistenciaM = new javax.swing.JButton();
        GuardarAsistenciaM = new javax.swing.JButton();
        AlumnoAsistencia = new javax.swing.JLabel();
        ComboMaestroRA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloAsistenciaM.setText("Registro de Asistecia Maestro");

        FechaAsistenciaM.setText("Fecha  :");

        TipoAsistenciaM.setText("Tipo : ");

        RegresarAsistenciaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48.png"))); // NOI18N
        RegresarAsistenciaM.setText("Regresar");
        RegresarAsistenciaM.setBorder(null);
        RegresarAsistenciaM.setBorderPainted(false);
        RegresarAsistenciaM.setContentAreaFilled(false);
        RegresarAsistenciaM.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48P.png"))); // NOI18N
        RegresarAsistenciaM.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48S.png"))); // NOI18N
        RegresarAsistenciaM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarAsistenciaMMouseClicked(evt);
            }
        });

        GuardarAsistenciaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48.png"))); // NOI18N
        GuardarAsistenciaM.setText("Guardar");
        GuardarAsistenciaM.setBorder(null);
        GuardarAsistenciaM.setBorderPainted(false);
        GuardarAsistenciaM.setContentAreaFilled(false);
        GuardarAsistenciaM.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48P.png"))); // NOI18N
        GuardarAsistenciaM.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48S.png"))); // NOI18N
        GuardarAsistenciaM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarAsistenciaMMouseClicked(evt);
            }
        });

        AlumnoAsistencia.setText("Maestro : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(TituloAsistenciaM)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TipoAsistenciaM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboTipoAsistenciaM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegresarAsistenciaM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarAsistenciaM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaAsistenciaM)
                            .addComponent(AlumnoAsistencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CalendarAsistenciaM, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ComboMaestroRA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TituloAsistenciaM)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlumnoAsistencia)
                    .addComponent(ComboMaestroRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaAsistenciaM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalendarAsistenciaM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoAsistenciaM)
                    .addComponent(ComboTipoAsistenciaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegresarAsistenciaM)
                    .addComponent(GuardarAsistenciaM))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarAsistenciaMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarAsistenciaMMouseClicked
        // TODO add your handling code here:
        
        int IDAMaestro = ComboMaestroRA.getItemAt(ComboMaestroRA.getSelectedIndex()).getIDMaestro();
        Date Date = CalendarAsistenciaM.getDate();
        long Fecha = Date.getTime();
        java.sql.Date FechaA = new java.sql.Date(Fecha);
        int IDTipoAsitenciaM = ComboTipoAsistenciaM.getItemAt(ComboMaestroRA.getSelectedIndex()).getIDTipoAsistencia();
        
        PreparedStatement PstRA = null;
        
        try{
            PstRA = RAsitenciaConexion.getConnection().prepareStatement("insert into asistenciamaestros values(null,?,?,?)");
            PstRA.setDate(1, FechaA);
            PstRA.setInt(2, IDAMaestro);
            PstRA.setInt(3, IDTipoAsitenciaM);
            
        }catch(Exception ERA){
            JOptionPane.showMessageDialog(null, "Error " + ERA);
        }
        
    }//GEN-LAST:event_GuardarAsistenciaMMouseClicked

    private void RegresarAsistenciaMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarAsistenciaMMouseClicked
        // TODO add your handling code here:
        if (VAsistenciaM == null){
            VAsistencia.VRasistenciaM = null;
            VAsistenciaM = new VAsistencia(Mod);
            VAsistenciaM.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_RegresarAsistenciaMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RAsistenciaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RAsistenciaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RAsistenciaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RAsistenciaMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RAsistenciaMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlumnoAsistencia;
    private com.toedter.calendar.JDateChooser CalendarAsistenciaM;
    private javax.swing.JComboBox<Maestro> ComboMaestroRA;
    private javax.swing.JComboBox<Asistencia> ComboTipoAsistenciaM;
    private javax.swing.JLabel FechaAsistenciaM;
    private javax.swing.JButton GuardarAsistenciaM;
    private javax.swing.JButton RegresarAsistenciaM;
    private javax.swing.JLabel TipoAsistenciaM;
    private javax.swing.JLabel TituloAsistenciaM;
    // End of variables declaration//GEN-END:variables

}
