/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Conectar;
import Login.Usuario;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Poot
 */
public class RegistroUsuario extends javax.swing.JFrame {
    public Conectar ConexionRU = new Conectar();
    Usuario Mod;
    public static Registros VRegistroU;

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }

    public RegistroUsuario(Usuario Mod) {
        initComponents();
        this.Mod = Mod;
        Usuario ComboUsuario = new Usuario();
        ComboUsuario.MostrarUsuario(ComboUsuarioRU);       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngreUsuarioRU = new javax.swing.JTextField();
        IngreContraseñaRU = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtRegresarRU = new javax.swing.JToggleButton();
        BtGuardarUsuario = new javax.swing.JToggleButton();
        ComboUsuarioRU = new javax.swing.JComboBox<>();
        TipoUsuarioRU = new javax.swing.JLabel();
        ContraseñaRU = new javax.swing.JLabel();
        UsuarioRU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IngreUsuarioRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreUsuarioRUActionPerformed(evt);
            }
        });

        IngreContraseñaRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreContraseñaRUActionPerformed(evt);
            }
        });

        jLabel1.setText("Registro de Usuario");

        BtRegresarRU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48.png"))); // NOI18N
        BtRegresarRU.setText("Regresar");
        BtRegresarRU.setBorder(null);
        BtRegresarRU.setBorderPainted(false);
        BtRegresarRU.setContentAreaFilled(false);
        BtRegresarRU.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48P.png"))); // NOI18N
        BtRegresarRU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48S.png"))); // NOI18N
        BtRegresarRU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegresarRUMouseClicked(evt);
            }
        });

        BtGuardarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48.png"))); // NOI18N
        BtGuardarUsuario.setText("Guardar");
        BtGuardarUsuario.setBorder(null);
        BtGuardarUsuario.setBorderPainted(false);
        BtGuardarUsuario.setContentAreaFilled(false);
        BtGuardarUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48P.png"))); // NOI18N
        BtGuardarUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48S.png"))); // NOI18N
        BtGuardarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtGuardarUsuarioMouseClicked(evt);
            }
        });

        TipoUsuarioRU.setText("Tipo de usuario : ");

        ContraseñaRU.setText("Contraseña : ");

        UsuarioRU.setText("Usuario : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtRegresarRU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtGuardarUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoUsuarioRU)
                            .addComponent(ContraseñaRU)
                            .addComponent(UsuarioRU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngreContraseñaRU, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(IngreUsuarioRU)
                            .addComponent(ComboUsuarioRU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngreUsuarioRU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioRU))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngreContraseñaRU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContraseñaRU))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboUsuarioRU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoUsuarioRU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtRegresarRU)
                    .addComponent(BtGuardarUsuario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtRegresarRUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegresarRUMouseClicked
        // TODO add your handling code here:
        if(VRegistroU == null){
            Registros.VRegistroUsuario = null;
            this.dispose();
            VRegistroU = new Registros(Mod);
            VRegistroU.setVisible(true);
        }        
        
        
    }//GEN-LAST:event_BtRegresarRUMouseClicked

    private void BtGuardarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtGuardarUsuarioMouseClicked
        // TODO add your handling code here:
        String NUsuarioText = this.IngreUsuarioRU.getText();
        String NContraseñaText = this.IngreContraseñaRU.getText();
        Usuario ITUsuario = new Usuario(ComboUsuarioRU.getItemAt(ComboUsuarioRU.getSelectedIndex()).getIDTipo() , ComboUsuarioRU.getItemAt(ComboUsuarioRU.getSelectedIndex()).getTipoUsuario());
        
        Usuario NUsuario = new Usuario(NUsuarioText,NContraseñaText, ITUsuario.getIDTipo(), ITUsuario.getTipoUsuario());
        
        
        PreparedStatement PstU = null;
        
        try{
            
            PstU = ConexionRU.getConnection().prepareStatement("insert into usuario values(null,?,?,?)");
            PstU.setString(1, NUsuario.getUsuario());
            PstU.setString(2, NUsuario.getPassword());
            PstU.setInt(3, NUsuario.getIDTipo());
            PstU.executeUpdate();
            
            IngreUsuarioRU.setText("");
            IngreContraseñaRU.setText("");
            
            JOptionPane.showMessageDialog(null, "Usuario Registrado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
        
    }//GEN-LAST:event_BtGuardarUsuarioMouseClicked

    private void IngreUsuarioRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreUsuarioRUActionPerformed
        // TODO add your handling code here:
        IngreUsuarioRU.transferFocus();
    }//GEN-LAST:event_IngreUsuarioRUActionPerformed

    private void IngreContraseñaRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreContraseñaRUActionPerformed
        // TODO add your handling code here:
        IngreContraseñaRU.transferFocus();
    }//GEN-LAST:event_IngreContraseñaRUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtGuardarUsuario;
    private javax.swing.JToggleButton BtRegresarRU;
    private javax.swing.JComboBox<Usuario> ComboUsuarioRU;
    private javax.swing.JLabel ContraseñaRU;
    private javax.swing.JTextField IngreContraseñaRU;
    private javax.swing.JTextField IngreUsuarioRU;
    private javax.swing.JLabel TipoUsuarioRU;
    private javax.swing.JLabel UsuarioRU;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
