/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Conectar;
import Login.Usuario;
import Modulos.Maestro;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Daniel Poot
 */
public class RegistroMaestro extends javax.swing.JFrame {
    private Conectar ConexionRM = new Conectar();
    public static Registros VRegistrosM;
    Usuario Mod;
    /**
     * Creates new form RegistroMaestro
     */
    public RegistroMaestro() {
        initComponents();
    }
    
    public RegistroMaestro(Usuario Mod) {
        this.Mod = Mod;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreRM = new javax.swing.JLabel();
        ApellidoPaternoRM = new javax.swing.JLabel();
        ApellidoMaternoRM = new javax.swing.JLabel();
        EdadRM = new javax.swing.JLabel();
        FechaIngresoRM = new javax.swing.JLabel();
        TelefonoRM = new javax.swing.JLabel();
        ExpRM = new javax.swing.JLabel();
        IngreNombreRM = new javax.swing.JTextField();
        IngreApellidoPaternoRM = new javax.swing.JTextField();
        IngreApellidoMaternoRM = new javax.swing.JTextField();
        IngreEdadRM = new javax.swing.JTextField();
        IngreExpRM = new javax.swing.JTextField();
        IngreTelefonoRM = new javax.swing.JTextField();
        IngreFechaIngresoRM = new com.toedter.calendar.JDateChooser();
        BtFotoRM = new javax.swing.JToggleButton();
        BtRegresarRM = new javax.swing.JToggleButton();
        BtGuardarRM = new javax.swing.JToggleButton();
        RutaFotoRM = new javax.swing.JTextField();
        MostrarFotoRM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Maestro");

        NombreRM.setText("Nombre : ");

        ApellidoPaternoRM.setText("Apellido Paterno  : ");

        ApellidoMaternoRM.setText("Apellido Materno : ");

        EdadRM.setText("Edad : ");

        FechaIngresoRM.setText("Fecha Ingreso : ");

        TelefonoRM.setText("Telefono : ");

        ExpRM.setText("Años de experiencia : ");

        IngreNombreRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreNombreRMActionPerformed(evt);
            }
        });

        IngreApellidoPaternoRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreApellidoPaternoRMActionPerformed(evt);
            }
        });

        IngreApellidoMaternoRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreApellidoMaternoRMActionPerformed(evt);
            }
        });

        IngreEdadRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreEdadRMActionPerformed(evt);
            }
        });

        IngreExpRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreExpRMActionPerformed(evt);
            }
        });

        IngreTelefonoRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreTelefonoRMActionPerformed(evt);
            }
        });

        BtFotoRM.setText("Foto");
        BtFotoRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFotoRMActionPerformed(evt);
            }
        });

        BtRegresarRM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48.png"))); // NOI18N
        BtRegresarRM.setText("Regresar");
        BtRegresarRM.setBorder(null);
        BtRegresarRM.setBorderPainted(false);
        BtRegresarRM.setContentAreaFilled(false);
        BtRegresarRM.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48P.png"))); // NOI18N
        BtRegresarRM.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48S.png"))); // NOI18N
        BtRegresarRM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegresarRMMouseClicked(evt);
            }
        });
        BtRegresarRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegresarRMActionPerformed(evt);
            }
        });

        BtGuardarRM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48.png"))); // NOI18N
        BtGuardarRM.setText("Guardar");
        BtGuardarRM.setBorder(null);
        BtGuardarRM.setBorderPainted(false);
        BtGuardarRM.setContentAreaFilled(false);
        BtGuardarRM.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48P.png"))); // NOI18N
        BtGuardarRM.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Guardar48S.png"))); // NOI18N
        BtGuardarRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarRMActionPerformed(evt);
            }
        });

        RutaFotoRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaFotoRMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MostrarFotoRM, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExpRM)
                                    .addComponent(TelefonoRM)
                                    .addComponent(FechaIngresoRM)
                                    .addComponent(EdadRM)
                                    .addComponent(ApellidoMaternoRM)
                                    .addComponent(ApellidoPaternoRM)
                                    .addComponent(NombreRM)
                                    .addComponent(BtFotoRM))
                                .addGap(60, 76, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(IngreNombreRM)
                                    .addComponent(IngreApellidoPaternoRM, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(IngreApellidoMaternoRM, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(IngreEdadRM, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(IngreExpRM, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(IngreTelefonoRM, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(IngreFechaIngresoRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RutaFotoRM)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtRegresarRM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtGuardarRM)))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreRM)
                    .addComponent(IngreNombreRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoPaternoRM)
                    .addComponent(IngreApellidoPaternoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoMaternoRM)
                    .addComponent(IngreApellidoMaternoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadRM)
                    .addComponent(IngreEdadRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaIngresoRM)
                    .addComponent(IngreFechaIngresoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoRM)
                    .addComponent(IngreTelefonoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpRM)
                    .addComponent(IngreExpRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtFotoRM)
                    .addComponent(RutaFotoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(MostrarFotoRM, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGuardarRM)
                    .addComponent(BtRegresarRM))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreTelefonoRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreTelefonoRMActionPerformed
        // TODO add your handling code here:
        IngreTelefonoRM.transferFocus();
    }//GEN-LAST:event_IngreTelefonoRMActionPerformed

    private void BtRegresarRMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegresarRMMouseClicked
        // TODO add your handling code here:
        
        if(VRegistrosM == null)
        {
            Registros.VRegistroMaestro = null;
            this.dispose();
            VRegistrosM = new Registros(Mod);
            VRegistrosM.setVisible(true);
        }
        
        
    }//GEN-LAST:event_BtRegresarRMMouseClicked

    private void BtFotoRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFotoRMActionPerformed
        // TODO add your handling code here:
        JFileChooser ImagenMaestro = new JFileChooser();
        FileNameExtensionFilter Filtro = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        ImagenMaestro.setFileFilter(Filtro);
        
        int Ventana = ImagenMaestro.showOpenDialog(this);
        if(Ventana == JFileChooser.APPROVE_OPTION){
            String RutaRM = ImagenMaestro.getSelectedFile().getAbsolutePath();
            RutaFotoRM.setText(RutaRM);
            
            Image FotoAlumno = getToolkit().getImage(RutaFotoRM.getText());
            
            FotoAlumno = FotoAlumno.getScaledInstance(90, 50, Image.SCALE_DEFAULT);
            MostrarFotoRM.setIcon(new ImageIcon(FotoAlumno));
        }
    }//GEN-LAST:event_BtFotoRMActionPerformed

    private void BtGuardarRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarRMActionPerformed
        // TODO add your handling code here:
        String NombreM = this.IngreNombreRM.getText();
        String ApellidoPM = this.IngreApellidoPaternoRM.getText();
        String ApellidoMM = this.IngreApellidoMaternoRM.getText();
        int EdadM = Integer.parseInt(this.IngreEdadRM.getText());
        
        //Creo un objeto fecha diseñado para poder ser pasado a la BD
        Date DateM = IngreFechaIngresoRM.getDate();
        long FechaM = DateM.getTime();
        java.sql.Date FechaMSQL = new java.sql.Date(FechaM);
        
        long TelefonoNM = Long.parseLong(this.IngreTelefonoRM.getText());
        int ExperienciaM = Integer.parseInt(this.IngreExpRM.getText());
        
        
        Maestro NMaestro = new Maestro(FechaMSQL,ExperienciaM, NombreM, ApellidoPM,ApellidoMM , EdadM, TelefonoNM);
        ///////////////////Ingresar ruta de la foto /////////////////////////////
        
        File RutImageM = new File(RutaFotoRM.getText());        
        
                
        PreparedStatement PstM = null;
        
        try{    
            
            
            
            byte[] IconoM = new byte[(int)RutImageM.length()];
            InputStream input = new FileInputStream(RutImageM);
            input.read(IconoM);
            NMaestro.setFotografia(IconoM);
            
            PstM = ConexionRM.getConnection().prepareStatement("insert into maestros values(null,?,?,?,?,?,?,?,?)");
            PstM.setString(1, NMaestro.getNombre());
            PstM.setString(2, NMaestro.getApellidoPaterno());
            PstM.setString(3, NMaestro.getApellidoMaterno());
            PstM.setInt(4, NMaestro.getEdad());
            PstM.setDate(5, NMaestro.getFechaInicio());
            PstM.setLong(6, NMaestro.getNumCelular());
            PstM.setBytes(7,NMaestro.getFotografia());    //Falta poner los datos para poner la foto
            PstM.setInt(8,NMaestro.getAñosExp());
            
            
            
            PstM.executeUpdate();
            
            IngreNombreRM.setText("");
            IngreApellidoPaternoRM.setText("");
            IngreApellidoMaternoRM.setText("");
            IngreEdadRM.setText("");
            IngreTelefonoRM.setText("");
            IngreExpRM.setText("");
                    
            JOptionPane.showMessageDialog(null, "Conectado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
                
        
    }//GEN-LAST:event_BtGuardarRMActionPerformed

    private void IngreNombreRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreNombreRMActionPerformed
        // TODO add your handling code here:
        
        IngreNombreRM.transferFocus();
    }//GEN-LAST:event_IngreNombreRMActionPerformed

    private void IngreApellidoPaternoRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreApellidoPaternoRMActionPerformed
        // TODO add your handling code here:
        
        IngreApellidoPaternoRM.transferFocus();
    }//GEN-LAST:event_IngreApellidoPaternoRMActionPerformed

    private void IngreApellidoMaternoRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreApellidoMaternoRMActionPerformed
        // TODO add your handling code here:
        IngreApellidoMaternoRM.transferFocus();
    }//GEN-LAST:event_IngreApellidoMaternoRMActionPerformed

    private void IngreEdadRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreEdadRMActionPerformed
        // TODO add your handling code here:
        IngreEdadRM.transferFocus();
    }//GEN-LAST:event_IngreEdadRMActionPerformed

    private void IngreExpRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreExpRMActionPerformed
        // TODO add your handling code here:
        IngreExpRM.transferFocus();
    }//GEN-LAST:event_IngreExpRMActionPerformed

    private void BtRegresarRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegresarRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtRegresarRMActionPerformed

    private void RutaFotoRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaFotoRMActionPerformed
        // TODO add your handling code here:
        RutaFotoRM.transferFocus();
    }//GEN-LAST:event_RutaFotoRMActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]){

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMaternoRM;
    private javax.swing.JLabel ApellidoPaternoRM;
    private javax.swing.JToggleButton BtFotoRM;
    private javax.swing.JToggleButton BtGuardarRM;
    private javax.swing.JToggleButton BtRegresarRM;
    private javax.swing.JLabel EdadRM;
    private javax.swing.JLabel ExpRM;
    private javax.swing.JLabel FechaIngresoRM;
    private javax.swing.JTextField IngreApellidoMaternoRM;
    private javax.swing.JTextField IngreApellidoPaternoRM;
    private javax.swing.JTextField IngreEdadRM;
    private javax.swing.JTextField IngreExpRM;
    private com.toedter.calendar.JDateChooser IngreFechaIngresoRM;
    private javax.swing.JTextField IngreNombreRM;
    private javax.swing.JTextField IngreTelefonoRM;
    private javax.swing.JLabel MostrarFotoRM;
    private javax.swing.JLabel NombreRM;
    private javax.swing.JTextField RutaFotoRM;
    private javax.swing.JLabel TelefonoRM;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
