/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Login.Usuario;

/**
 *
 * @author Daniel Poot
 */
public class Registros extends javax.swing.JFrame {
    public static Menu VMenu;
    public static RegistroAlumno VRegistroAlumno;
    public static RegistroMaestro VRegistroMaestro;
    public static RegistroUsuario VRegistroUsuario;
    Usuario Mod;
    /**
     * Creates new form Registros
     */
    public Registros() {
        initComponents();
    }
    
    public Registros(Usuario Mod){
        initComponents();
        setLocationRelativeTo(null);
        this.Mod = Mod;
        if(Mod.getIDTipo() == 1)
        {
               
        }else if(Mod.getIDTipo() == 2)
        {
           BtRegistroUsuario.setVisible(false); 
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtRegistroAlumnos = new javax.swing.JButton();
        BtRegistroMaestro = new javax.swing.JButton();
        BtRegistroUsuario = new javax.swing.JButton();
        BtRegresarRegistrar = new javax.swing.JButton();
        RegistrarR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        BtRegistroAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirAlumno.png"))); // NOI18N
        BtRegistroAlumnos.setText("Alumno");
        BtRegistroAlumnos.setBorder(null);
        BtRegistroAlumnos.setBorderPainted(false);
        BtRegistroAlumnos.setContentAreaFilled(false);
        BtRegistroAlumnos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirAlumnoP.png"))); // NOI18N
        BtRegistroAlumnos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirAlumnoS.png"))); // NOI18N
        BtRegistroAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegistroAlumnosMouseClicked(evt);
            }
        });

        BtRegistroMaestro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirProfesor.png"))); // NOI18N
        BtRegistroMaestro.setText("Mestro");
        BtRegistroMaestro.setBorder(null);
        BtRegistroMaestro.setBorderPainted(false);
        BtRegistroMaestro.setContentAreaFilled(false);
        BtRegistroMaestro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirProfesorP.png"))); // NOI18N
        BtRegistroMaestro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirProfesorS.png"))); // NOI18N
        BtRegistroMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegistroMaestroMouseClicked(evt);
            }
        });

        BtRegistroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirUsuario.png"))); // NOI18N
        BtRegistroUsuario.setText("Usuario");
        BtRegistroUsuario.setBorder(null);
        BtRegistroUsuario.setBorderPainted(false);
        BtRegistroUsuario.setContentAreaFilled(false);
        BtRegistroUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirUsuarioP.png"))); // NOI18N
        BtRegistroUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/AñadirUsuarioS.png"))); // NOI18N
        BtRegistroUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegistroUsuarioMouseClicked(evt);
            }
        });

        BtRegresarRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48.png"))); // NOI18N
        BtRegresarRegistrar.setText("Regresar");
        BtRegresarRegistrar.setBorder(null);
        BtRegresarRegistrar.setBorderPainted(false);
        BtRegresarRegistrar.setContentAreaFilled(false);
        BtRegresarRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48P.png"))); // NOI18N
        BtRegresarRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/Salir48S.png"))); // NOI18N
        BtRegresarRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegresarRegistrarMouseClicked(evt);
            }
        });

        RegistrarR.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        RegistrarR.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtRegistroAlumnos)
                .addGap(18, 18, 18)
                .addComponent(BtRegistroMaestro)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(BtRegistroUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(RegistrarR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BtRegresarRegistrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(RegistrarR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtRegistroAlumnos)
                    .addComponent(BtRegistroMaestro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtRegistroUsuario)
                .addGap(44, 44, 44)
                .addComponent(BtRegresarRegistrar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtRegistroAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegistroAlumnosMouseClicked
        // TODO add your handling code here:
        if(VRegistroAlumno == null)
        {
            RegistroAlumno.VRegistros = null;
            this.dispose();
            VRegistroAlumno = new RegistroAlumno(Mod);
            VRegistroAlumno.setVisible(true);
        }
        
        
    }//GEN-LAST:event_BtRegistroAlumnosMouseClicked

    private void BtRegistroMaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegistroMaestroMouseClicked
        // TODO add your handling code here:
        if(VRegistroMaestro == null)
        {
            RegistroMaestro.VRegistrosM = null;
            this.dispose();
            VRegistroMaestro = new RegistroMaestro(Mod);
            VRegistroMaestro.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_BtRegistroMaestroMouseClicked

    private void BtRegresarRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegresarRegistrarMouseClicked
        // TODO add your handling code here:
        
        if(VMenu == null){
            Menu.VRegistro = null;
            this.dispose();
            VMenu = new Menu(Mod);
            VMenu.setVisible(true);
        }
        
    }//GEN-LAST:event_BtRegresarRegistrarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void BtRegistroUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegistroUsuarioMouseClicked
        // TODO add your handling code here:
        if(VRegistroUsuario == null){
            RegistroUsuario.VRegistroU = null;
            this.dispose();
            VRegistroUsuario = new RegistroUsuario(Mod);
            VRegistroUsuario.setVisible(true);
        }
    }//GEN-LAST:event_BtRegistroUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtRegistroAlumnos;
    private javax.swing.JButton BtRegistroMaestro;
    private javax.swing.JButton BtRegistroUsuario;
    private javax.swing.JButton BtRegresarRegistrar;
    private javax.swing.JLabel RegistrarR;
    // End of variables declaration//GEN-END:variables
}
